# Source: omega/templates/rbac/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flaskapi
  labels:
    app.kubernetes.io/name: flaskapi
    app.kubernetes.io/instance: flaskapi
---
# Source: omega/templates/rbac/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flaskapi
  labels:
    app.kubernetes.io/name: flaskapi
    app.kubernetes.io/instance: flaskapi
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "configmaps"
      - "services"
      - "endpoints"
      - "secrets"
    verbs:
      - "create"
      - "list"
      - "get"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "get"
---
# Source: omega/templates/rbac/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flaskapi
  labels:
    app.kubernetes.io/name: flaskapi
    app.kubernetes.io/instance: flaskapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flaskapi
subjects:
  - kind: ServiceAccount
    name: flaskapi
