# Source: omega/templates/networking/service.yml
apiVersion: v1
kind: Service
metadata:
  name: flaskapi
  labels:
    app.kubernetes.io/name: flaskapi
    app.kubernetes.io/instance: flaskapi
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: flaskapi
    app.kubernetes.io/instance: flaskapi
    app.kubernetes.io/component: flaskapi
